STACK-1559: Added support to allow templates to be used from the shared partition
a10networks/acos-client pull request #293
Opened 2020-09-16 12:56 UTC by NehaKembalkarA10

## Description
Added support for attaching templates from shared partition to virtual-port, service-group and server of a l3v partition.

## Jira Ticket
https://a10networks.atlassian.net/browse/STACK-1559

## Technical Approach
**For listener:**
- Added support for `template-http-shared` and `shared-partition-http-template` params to attach shared http templates  to a virtual-port.
- Added support for `template-tcp-shared` and `shared-partition-tcp` params to attach shared tcp templates  to a virtual-port.
- Added support for `template-policy-shared` and `shared-partition-policy-template` params to attach shared policy templates  to a virtual-port.
- Added support for `template-virtual-port-shared` and `shared-partition-virtual-port-template` params to attach shared virtual port templates  to a virtual-port.

**For pool:**
- Added support for `template-policy-shared` and `shared-partition-policy-template` params to attach shared policy templates  to a service-group.

2020-09-16 13:30 UTC, OmkarTelee-A10 approved these changes

2020-09-17 04:03 UTC, afrin-chakure-a10 requested changes

2020-09-17 05:29 UTC, NehaKembalkarA10 commented on acos_client/v30/slb/virtual_port.py
> +            elif virtual_port_templates.get('template-client-ssl-shared'):
Removed this part.

2020-09-17 06:18 UTC, afrin-chakure-a10 approved these changes

2020-09-17 07:29 UTC, merged