Removed override-port option
a10networks/acos-client pull request #366
Opened 2021-12-09 06:51 UTC by sana-a10

Removed **'override-port'** parameter to avoid health monitor port overriding

2021-12-09 07:51 UTC, ytsai-a10 requested changes

2021-12-09 07:51 UTC, ytsai-a10 commented on acos_client/v30/slb/hm.py
> -            params['monitor']['override-port'] = int(port)
Please provide an option for other user that still able to use the override-port

2021-12-10 21:07 UTC, hthompson-a10 approved these changes

2021-12-13 05:32 UTC, ytsai-a10 approved these changes

2021-12-13 05:32 UTC, merged